name: CI nodejs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  continuous-integration:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - run: docker image build -t nodejs_image ./
      - run: docker run nodejs_image sh -c "npm run lint && npm test && npm run build" 
  continuous-deployment:
    runs-on: ubuntu-22.04
    needs: continuous-integration
    if: contains('refs/heads/main', github.ref)
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: yaamto69
          password: ${{ secrets.DOCKERHUB }}
      - name: Push if on `main`
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./
          tags: yaamto69/nodeproject:latest
  continuous-delivery:
    runs-on: ubuntu-22.04
    needs: [continuous-integration, continuous-deployment]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: yaamto69
          password: ${{ secrets.DOCKERHUB }}
      - name: Push if on `main`
        uses: docker/build-push-action@v4
        
        with:
          push: true
          context: ./
          tags: yaamto69/sayhello:${{ github.ref_name }}