name: CI nodejs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  nodejs_test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - run: docker image build -t nodejs_image ./
      - run: docker run nodejs_image sh -c "npm run lint && npm test && npm run build" 
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          username: yaamto69
          password: ${{ secrets.DOCKERHUB }}